#! /usr/bin/env zsh

bspc config border_width         8
bspc config window_gap          25

if [ "$(hostname)" = turing ]; then
    #desktops="code,terms,web,bg,misc"
    #desktops="1,2,3,4,5"
    desktops_left="1,2"
    desktops_middle="3,4,5,6,7"
    desktops_right="8,9"

    bspc monitor HDMI2 -d `eval echo 1/{$desktops_left}`
    bspc monitor DP1 -d `eval echo 2/{$desktops_middle}`
    bspc monitor HDMI1 -d `eval echo 3/{$desktops_right}`

    # Work around bottom padding the height of lemonbar even if it's not on the monitor.
    bspc config -d 1/1 bottom_padding -28
    bspc config -d 1/2 bottom_padding -28

else
    desktops="1,2,3,4,5,6,7,8,9"
    i=1
    for monitor in $(bspc query -M); do
    bspc monitor $monitor \
            -n "$i" \
            -d `eval echo $i/{$desktops}`
        let i++
    done
    NMON=$i
    unset i

fi

for desktop in $(bspc query -D); do
    bspc config -d $desktop top_padding 0
    bspc config -d $desktop bottom_padding 0
    bspc config -d $desktop left_padding 0
    bspc config -d $desktop right_padding 0
done

#declare -a middleDesktops=("2/3" "2/4" "2/5" "2/6" "2/7")
#for desktop in $(bspc query -D); do
#for desktop in ${middleDesktops[@]}; do
#    bspc config -d $desktop top_padding 14
#    bspc config -d $desktop bottom_padding 14
#done


#bspc config top_padding 14 

bspc config pointer_modifier mod4

# Visual options
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
# bspc config auto_alternate true
# bspc config auto_cancel true
bspc config normal_border_color "#332d29"
bspc config active_border_color "#817267"
#bspc config focused_border_color "#504339"
bspc config focused_border_color "#005080"
# bspc config presel_border_color "#9a875f"
bspc config presel_feedback_color "#9a875f"
# bspc config urgent_border_color "#9f7155"
# bspc config focused_locked_border_color "#9a875f"
# bspc config normal_frame_opacity 0.0
# bspc config focused_frame_opacity 0.1


# Rules
#bspc rule -a Chromium state=floating manage=on
#bspc rule -a chromium-browser state=floating manage=on
#bspc rule -a Chromium-browser state=floating manage=on
#bspc rule -a vlc state=floating manage=off

#bspc rule -a Skype pseudo_tiled=on
#bspc rule -a Spotify pseudo_tiled=on
#bspc rule -a Thunar pseudo_tiled=on
#bspc rule -a Skype pseudo_tiled=on
#bspc rule -a File-roller pseudo_tiled=on
#bspc rule -a Transmission-gtk pseudo_tiled=on
#bspc rule -a Conky sticky=on manage=off lower=on
#bspc rule -a astime sticky=on
#bspc rule -a dmenu state=floating manage=off
bspc config external_rules_command ~/scripts/bspwm_external_rules.sh

# /home/sunn/.config/bspwm/panel/panel &
