#!/bin/sh

pkill lemonbar
if [ "$(hostname)" = nixos ]; then
    ~/scripts/bar_top.sh    | lemonbar -p    -f "Fixedsys Excelsior 3.01:size=12" | sh &
    ~/scripts/bar_bottom.sh | lemonbar -p -b -f "Fixedsys Excelsior 3.01:size=12" | sh &
elif [ "$(hostname)" = shadow ]; then
    ~/scripts/bar_top.sh    | lemonbar -p    -B \#80000000 | sh &
    ~/scripts/bar_bottom.sh | lemonbar -p -b -B \#80000000 | sh &
fi

